# Generated by Django 6.0.7 on 2026-10-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_to_secret_mark', models.TextField(help_text="Detailed answer to the finder's verification question")),
                ('proof_image', models.ImageField(blank=True, help_text='Optional: Photo of receipt, matching sticker, ID, or old photo with the item', null=True, upload_to='claims/proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACCEPTED', 'Accepted - Verification Succeeded'), ('REJECTED', 'Rejected - Proof Mismatch')], default='PENDING', max_length=20)),
                ('finder_notes', models.TextField(blank=True, help_text='Notes from finder or meeting point instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'claimant')},
            },
        ),
    ]
