# Generated by Django 6.0.7 on 2026-10-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='BAIUST Student or Staff ID', max_length=30, unique=True)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering (CSE)'), ('EEE', 'Electrical & Electronic Engineering (EEE)'), ('CE', 'Civil Engineering (CE)'), ('BBA', 'Business Administration (BBA)'), ('ENG', 'English'), ('LAW', 'Law')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
