# Generated by Django 6.0.7 on 2026-10-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='bi-box-seam', help_text='Bootstrap icon class e.g. bi-laptop, bi-card-text', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('item_type', models.CharField(choices=[('LOST', 'Lost Item'), ('FOUND', 'Found Item')], default='LOST', max_length=10)),
                ('primary_image', models.ImageField(upload_to='items/')),
                ('additional_image', models.ImageField(blank=True, null=True, upload_to='items/additional/')),
                ('location', models.CharField(choices=[('Academic Building 1', 'Academic Building 1'), ('Academic Building 2', 'Academic Building 2'), ('Central Library', 'Central Library'), ('Main Cafeteria / Canteen', 'Main Cafeteria / Canteen'), ('Boys Hall', 'Boys Hall'), ('Girls Hall', 'Girls Hall'), ('Playground / Sports Ground', 'Playground / Sports Ground'), ('Campus Bus', 'Campus Bus'), ('Computer Lab (Lab 1-4)', 'Computer Lab (Lab 1-4)'), ('ECE/EEE Lab', 'ECE/EEE Lab'), ('Admin Building', 'Admin Building'), ('Mosque Area', 'Mosque Area'), ('Campus Gate / Reception', 'Campus Gate / Reception'), ('Other Campus Location', 'Other Campus Location')], max_length=100)),
                ('specific_location_details', models.CharField(help_text='e.g. Room 304, 2nd row bench, or Near Water Cooler', max_length=255)),
                ('date_occurred', models.DateField(help_text='Date the item was lost or found')),
                ('description', models.TextField(help_text='Detailed description of color, brand, condition, tags, etc.')),
                ('secret_mark_question', models.CharField(blank=True, help_text='For FOUND items: Ask a question only the owner can answer (e.g. lock screen wallpaper, inside sticker, contents of purse)', max_length=255)),
                ('current_custody', models.CharField(blank=True, choices=[('With Finder', 'With Finder (Keep in own custody)'), ('Deposited at Security Office', 'Deposited at Security Office'), ('Deposited at Dept Office', 'Deposited at Dept Office'), ('Campus Reception / Gate', 'Campus Reception / Gate'), ('Central Library Desk', 'Central Library Desk')], default='With Finder', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Active / Listed'), ('MATCHED', 'Potential Match Found'), ('RETURNED', 'Returned / Resolved')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.category')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
